sci_phi_blog/accs/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import UserCreateView, UserRegisterView, UserChangeView, AccountChangePasswordView, UserProfileView, \
    EditUserProfileView, EditUserProfileSettingsView, CreateUserProfileView, SaveJSONView

urlpatterns = [
    path('create_user', UserCreateView.as_view(), name="create_user"),
    path('register', UserRegisterView.as_view(), name='register'),
    path('edit', UserChangeView.as_view(), name="edit_user"),
    path('create/profile', CreateUserProfileView.as_view(), name='create_profile'),
    path('<int:pk>/profile', UserProfileView.as_view(), name="profile_page"),
    path('<int:pk>/profile/edit_profile', EditUserProfileView.as_view(), name="edit_profile_page"),
    path('<int:pk>/profile/save', SaveJSONView.as_view(), name="save_json"),
    path('profile_settings', EditUserProfileSettingsView.as_view(), name="edit_profile"),
]

sci_phi_blog/arts/urls.py
from .views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, \
    show_categories, show_languages, ArticleByLanguageView, ResponseView, ResponseUpdateView, ResponseDeleteView, \
    ResponseToResponseView, ShowResponsesToResponseView
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'arts'

urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create_article'),
    path('all/', ArticleListView.as_view(), name = 'all'),
    path('all/categories', show_categories, name ='categories'),
    path('all/languages', show_languages, name='languages'),
    path('article/<int:pk>', ArticleDetailView.as_view(), name='article'),
    path('article/<int:pk>/update', ArticleUpdateView.as_view(), name='update_article'),
    path('article/<int:pk>/delete', ArticleDeleteView.as_view(), name='delete_article'),
    path('article/<int:pk>/response', ResponseView.as_view(), name='comment_article'),
    path('article/<int:pk>/response/<int:pk_2>', ResponseUpdateView.as_view(), name='update_comment'),
    path('article/<int:pk>/response/<int:pk_2>/delete', ResponseDeleteView.as_view(), name='delete_comment'),
    path('article/response_to_response/<int:pk>', ResponseToResponseView.as_view(), name='response_to_response'),
    path('article/response_to_response/<int:pk>/all_responses', ShowResponsesToResponseView.as_view(), name='all_responses_to_response'),
    path('languages/<str:lang>', ArticleByLanguageView.as_view(), name='articles_by_lang'),
]

sci_phi_blog/sci_phi_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static

from accs.views import AccountChangePasswordView

app_name = "home"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('user/', include('accs.urls')),
    path('articles/', include('arts.urls')),
    path('user/profile/', views.profile_redirect, name='profile_redirect'),
    path('password/', AccountChangePasswordView.as_view(), name="password"),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sci_phi_blog/arts/models.py
from django.core.validators import MinLengthValidator
from django.db import models
from enum import Enum
from ckeditor.fields import RichTextField

from accs.models import Account
from django.urls import reverse_lazy


class Languages(Enum):
    ENGLISH = 'English'
    DUTCH = 'Nederlands'
    FRENCH = 'Français'
    GERMAN = 'Deutsch'
    JAPANESE = '日本'

    @classmethod
    def choices(cls):
        return [(key.value, key.name) for key in cls]

class Categories(Enum):
    GENERAL = 'General';
    PHILOSPHY = 'Philosophy'
    SCIENCE = 'Science'
    PSYCHOLOGY = 'Psychology'
    PRODUCTIVITY = 'Productivity'

    @classmethod
    def choices(cls):
        return [(key.value, key.name) for key in cls]

    @classmethod
    def lang_choice(cls, lang: str) -> bool:
        if lang in cls.value:
            return True
        else:
            return False


class Article(models.Model):
    title = models.CharField(null=False,
                             max_length=250,
                             validators=[MinLengthValidator(3, "Title must be at least three characters!")]
                             )
    #text = models.TextField(null=False, blank=False)
    text = RichTextField(null=True, blank=True)
    time_created = models.DateTimeField(verbose_name="time created", auto_now_add=True)
    last_edited = models.DateTimeField(verbose_name="last edited", auto_now=True)
    author = models.ForeignKey(Account, related_name="articles", on_delete=models.CASCADE)
    language = models.CharField(choices=Languages.choices(), default=Languages.ENGLISH, max_length=100)
    category = models.CharField(choices=Categories.choices(), default=Categories.GENERAL, max_length=50)
    background_picture = models.ImageField(null = True, blank=True, upload_to='images/')
    responses = models.ManyToManyField(Account, through='Response', related_name="responded_to")
    snippet = models.CharField(max_length=255)

    def get_absolute_url(self):
        return reverse_lazy("arts:article", kwargs={'pk':self.pk});


class Picture(models.Model):

    description = models.CharField(validators=[MinLengthValidator(5, "Please enter at least five characters!")],
                                   max_length=250)
    image = models.BinaryField(null = False)
    content_type = models.CharField(max_length=256, null=True, help_text="The MIMEType of the file")

class Response(models.Model):
    body = models.TextField(null=False, blank=False)
    time_created = models.DateTimeField(verbose_name="time created", auto_now_add=True)
    last_edited = models.DateTimeField(verbose_name="last edited", auto_now=True)
    author = models.ForeignKey(Account, related_name="responses", null=False, on_delete=models.CASCADE)
    response_to_response = models.ForeignKey('self', related_name="responded_by", null=True, on_delete=models.CASCADE)
    response_to_article = models.ForeignKey(Article, related_name="response_comments", null=True, on_delete=models.CASCADE)

sci_phi_blog/arts/forms.py
import django.forms as forms;
from django.core.files.uploadedfile import InMemoryUploadedFile

from .models import Article, Picture, Response


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'text','language','category','snippet','background_picture']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'form-control'}),
            'language': forms.Select(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'snippet': forms.Textarea(attrs={'class': 'form-control'}),
        }

class ResponseForm(forms.ModelForm):

    #def __init__(self, *args, **kwargs):
    #    self.user_to_add = kwargs.pop('user_to_add', None)
    #    print("Popped a kwarg")
     #   super(ResponseForm, self).__init__(**kwargs)

    class Meta:
        model = Response
        fields = ['body']
        widgets = {
            'body': forms.Textarea(attrs={'class':'form-control'})
        }

sci_phi_blog/arts/views.py
import json
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.urls import reverse_lazy, reverse, resolve
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from .models import Article, Languages, Categories, Response
from .forms import ArticleForm, ResponseForm


class ArticleCreateView(CreateView, LoginRequiredMixin):
    model = Article
    template_name = 'arts/art_form.html'
    success_url = reverse_lazy('about')

    def get(self, request):
        form = ArticleForm()
        for i in request:
            print(request[i])

        return render(request, self.template_name, { "form": form})

    def post(self, request):
        print("Posting ....")
        form = ArticleForm(request.POST, request.FILES)
        print(request.FILES)
        if not form.is_valid():
            print(form.errors.as_json())
            ctx = {"form": form}
            print("FOrm invalid")
            return render(request, self.template_name, ctx)

        art = form.save(commit = False)
        art.author = self.request.user

        art.save()
        return redirect(self.success_url)

class ArticleListView(LoginRequiredMixin, ListView):
    model = Article
    template_name = 'arts/art_list.html'
    success_url = reverse_lazy('arts:all')

    def get_queryset(self):
        qs = super().get_queryset().order_by('time_created').reverse()

        if self.request.GET.get("search") is not None:
            strval = self.request.GET["search"]
            q = Q(title__icontains=strval)|Q(text__icontains=strval)
            return qs.filter(q)

        return qs

class ArticleDetailView(LoginRequiredMixin, DetailView):
    model = Article
    template_name = 'arts/art_detail.html'

    def get(self, request, **kwargs):
        art = Article.objects.get(id=self.kwargs.get('pk'))
        print(art.response_comments.all())
        article_comments_with_responses = []
        for resp in art.response_comments.all():
            article_comments_with_responses.append(
                {"response" : resp,
                 "commented" : len(resp.responded_by.all()) > 0
                 }
            )
        ctx = {"art" : art, "resp_form" : ResponseForm(), "responses": article_comments_with_responses}
        return render(request, self.template_name, ctx)

class ArticleUpdateView(LoginRequiredMixin, UpdateView):
    model = Article
    template_name =  'arts/art_update.html'
    form_class = ArticleForm

    def get_form_kwargs(self):
        kwargs = super(ResponseView, self).get_form_kwargs()
        print("kwargs are: " + str(kwargs))
        kwargs['user_to_add'] = self.request.user
        return kwargs

    def get(self, request, pk=None):
        art = get_object_or_404(Article, id=pk, author=self.request.user)
        form = ArticleForm(instance=art)
        return render(self.request, self.template_name, {"form": form,
                                                         "art": art})

    def post(self, request, pk=None):
        form = ArticleForm(request.POST)
        if form.is_valid():
            art = get_object_or_404(Article, id=pk, author=self.request.user)
            art.title = request.POST["title"]
            art.text = request.POST["text"]
            art.language = request.POST["language"]
            art.category = request.POST["category"]
            art.snippet = request.POST["snippet"]
            art.background_picture = request.POST["background_picture"]

            art.save()
            return redirect(reverse('arts:all'))

        art = get_object_or_404(Article, id=pk, author=self.request.user)
        return render(request, self.template_name, {"form": form,
                                                    "art": art})



class ArticleDeleteView(LoginRequiredMixin, DeleteView):
    success_url = reverse_lazy('arts:all')
    template_name = 'arts/article_delete_confirm.html'
    model = Article

    def get_queryset(self):
        qs = super(DeleteView, self).get_queryset()
        return qs.filter(author=self.request.user)

class ResponseView(LoginRequiredMixin, CreateView):
    model = Response
    form_class = ResponseForm

    def get_form_kwargs(self):
        kwargs = super(ResponseView, self).get_form_kwargs()
        print("kwargs are: " + str(kwargs))
        kwargs['user_to_add'] = self.request.user
        return kwargs

    def post(self, request, pk):
        form = ResponseForm(request.POST)
        if form.is_valid():
            response = form.save(commit=False)
            print("Post is:"  + str(request.POST))
            response.author = self.request.user;
            print(self.kwargs)
            to_article = get_object_or_404(Article, id = pk)
            response.response_to_article = to_article
            response.save()
            print("Body is:"  + str(response.body))

            #return redirect(reverse_lazy("arts:article", kwargs={'pk': pk}))
            return redirect(response.response_to_article.get_absolute_url())

        else:
            return HttpResponse("Invalid")

class ResponseUpdateView(ResponseView):
    form_class = ResponseForm
    model = Response
    template_name = "arts/response_update.html"

    def get(self, request, **kwargs):
        print("Second key is: " + str(kwargs['pk_2']))
        response = get_object_or_404(Response, id=kwargs['pk_2'])
        form = ResponseForm(instance=response)
        print("form is: " + str(form))
        return render(request, self.template_name, {"form": form})


    def post(self, request, **kwargs):
        print("hey");
        article = get_object_or_404(Article, id=kwargs['pk']);
        form = ResponseForm(request.POST);
        if form.is_valid():
            response = get_object_or_404(Response, id=kwargs['pk_2'])
            response.body = form.cleaned_data['body'];
            response.save();
            return redirect(reverse_lazy("arts:article", kwargs = {"pk" : kwargs['pk']}))
        else:
            return HttpResponse(reverse_lazy("arts:article", kwargs = {"pk" : kwargs['pk']}))

    def form_valid(self, form):
        ## ONLY called when the view does not have any default implementation of POST or GET
        print("BIG MOM")
        return super().form_valid(form)

    def form_invalid(self, form):
        print("KAIDO")
        return HttpResponse("FORM IS INVALID FOOL")

class ResponseDeleteView(DeleteView):
    model = Response
    template_name = "arts/response_delete_confirm.html"

    def get_success_url(self, **keyword_arguments):
        ## I got it... kwargs is here than the name of a dict for all named ones :)
        return reverse_lazy("arts:article", kwargs = {"pk" : keyword_arguments['pk']})

    def post(self, request, **kwargs):
        resp = Response.objects.get(id=kwargs['pk_2'])
        resp.delete()
        print("Delete article of id: " + str(kwargs['pk_2']))
        ###WHY THE FUCK DOES THIS WHOLE KEYWORD ISSUE NOT WORK??
        ### APARENTLY, PK's in URLS are KEYWORD WITH DICTIONARY OF VALUES
        return redirect(self.get_success_url(pk = kwargs['pk']))


    def get(self, request, **kwargs):
        print("Getting...")
        return render(request, self.template_name, {})

class ResponseToResponseView(View):
    def post(self, request, **kwargs):

        print("In post")
        print("cookies are: " + str(request.COOKIES))
        print("body is: " + str(request.body))
        print("POST is: " + str(request.POST))
        data = json.loads(request.body)
        print("ID is: " + str(kwargs['pk']))
        print("data is: " + str(data['content']))

        target_response = get_object_or_404(Response, id=kwargs['pk'])

        response = Response(body=data['content'], author=self.request.user, response_to_response=target_response)
        response.save()

        return JsonResponse({"post": "post"})

    def get(self, request, **kwargs):
        return JsonResponse({"get": "get"})

class ShowResponsesToResponseView(View):
    def get(self, request, **kwargs):
        print("Start")
        response = get_object_or_404(Response, id=kwargs['pk'])
        all_responses = response.responded_by.all();
        all_responses_list = []
        for resp in all_responses:
            all_responses_list.append(
                {
                    "body": resp.body,
                    "id": resp.id,
                    "commented" : len(resp.responded_by.all()) > 0
                }
            )
        return JsonResponse(data=all_responses_list, safe=False)

def show_categories(request):

    cats = Categories.choices()
    cats_list = []

    for cat in cats:
        cats_list.append(cat[0])

    ctx = {"enums": cats_list}
    return render(request, 'arts/enum_list.html', ctx)

def show_languages(request):
    langs = Languages.choices()
    lang_list = []

    for lang in langs:
        lang_list.append(lang[0])


    ctx = {"enums": lang_list}
    return render(request, 'arts/enum_list.html', ctx)

class ArticleByLanguageView(ListView):
    model = Article

    def get(self, request, lang):
        print(lang)
        for choice in Languages.choices():
            if lang == choice[0]:
                articles_with_language = Article.objects.filter(language=lang)
                article_list = []

                for article in articles_with_language:
                    article_dict = {}
                    article_dict["id"] = article.id
                    article_dict["title"] = article.title
                    article_list.append(article_dict);

                return JsonResponse(article_list, safe=False)

        for choice in Categories.choices():
            if lang == choice[0]:
                articles_with_category = Article.objects.filter(category=lang)
                article_list = []

sci_phi_blog/arts/templates/arts/art_detail.html
{% extends "base_menu.html" %}
{% load static %}
{% block title %}
    {{art.title}}
{% endblock %}

{% block content %}
<div class="row" style="width: 100%;">
<div class="col-xs-12 article"  id="{{art.id}}">
    <h3>{{ art.title }}</h3>
    by: {{ art.author.username }}
    <br/>
    <br/>
    <p style="font-size: small; color: blue;">{{ art.text|safe}}</p>
    <br/>
        <hr>
    <br/>
    {% if user == art.author %}
    <a href="{% url 'arts:update_article' art.id%}"><i class="fa fa-pencil"></i></a>
    <a href="{% url 'arts:delete_article' art.id%}"><i class="fa fa-trash"></i></a>
    {% endif %}
</div>
<div class="w-100"></div>
<div id="personal" class="col-xs-12">
    {% if art.author.profile %}
        <a href="{% url 'profile_page' art.author.id %}">Profile</a> |
        {% if art.author.profile.facebook_url %}
        <a href="art.author.profile.facebook_url">Facebook</a> |
        {% endif %}
        {% if art.author.profile.twitter_url %}
        <a href="art.author.profile.twitter_url">Twitter</a> |
        {% endif %}
        {% if art.author.profile.instagram_url %}
        <a href="art.author.profile.instagram_url">Instagram</a> |
        {% endif %}
    <img src="{% static '{{art.author.profile.picture}}' %}" alt="A pic" class="rounded-circle" width="100" height="100">
    <div>
        <p>{{art.author.profile.bio| safe}}</p>
    </div>
    {% else %}
    <img src="{% static 'images/unknown_user.png' %}" alt="A pic" class="rounded-circle" width="100" height="100">
    {% endif %}
</div>
    </div>
    <form action="{% url 'arts:comment_article' art.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ resp_form.as_p }}
    <input type="submit" value="Post comment">
    </form>
{% for resp in responses %}
<div style="border: solid;
    border-width: 1px;" id="response_{{resp.response.id}}">
        <p>{{resp.response.body}}</p>
            <br>
        <p>by: {{resp.response.author }}</p>
        {% if user == resp.author %}
        <a href="{% url 'arts:update_comment' art.id resp.response.id %}">Edit</a>
        <a href="{% url 'arts:delete_comment' art.id resp.response.id %}">Delete</a>
        {% else %}
        <button class="btn btn-primary" onclick="createCommentForm({{resp.response.id}}, '{% url 'arts:delete_comment' art.id resp.response.id %}')">Comment</button>
        {% endif %}
        {% if resp.commented %}
        <a href="#" onclick="{ fetchResponses({{resp.response.id}}); return false;}"><b>show comments</b></a>
        {% endif %}
    </div>
{% endfor %}

<script>

const responseFactory = function(){
        this.createElement = function(type, body, id, commented){
            var responseElement;

            if (type === "response"){
                responseElement = new CommentResponse();
                responseElement.id = `response_${id}`;
                responseElement.body = body;
                responseElement.commented = commented;

            } else if (type === "form"){
                responseElement = new CommentForm();
                responseElement.id = `${id}`;
                responseElement.body = body;
                responseElement.commented = commented;
            }

            responseElement.create = function(){
                if (this.type === "response"){
                    div = document.createElement("div");
                    div.setAttribute("id", this.id);
                    p_body = document.createElement("p");
                    p_author = document.createElement("p");
                    p_body.textContent = this.body;
                    p_author.textContent = "by: " + "Jesus";
                    button = document.createElement("button");
                    button.setAttribute("class", "btn btn-primary");
                    button_text = document.createTextNode("Comment");
                    button.appendChild(button_text);
                    button.setAttribute("onclick", `createCommentForm(${id})`);

                    // add new button to remove via remove(this) and subsequent implementation

                    div.appendChild(p_body);
                    div.appendChild(document.createElement("br"))
                    div.appendChild(p_author);

                    div.appendChild(button);
                    if (this.commented === true){
                        b = document.createElement("b");
                        a = document.createElement("a");
                        a.setAttribute("href", "#");
                        a.setAttribute("onclick",`{fetchResponses(${id}); return false;}`)
                        a_text = document.createTextNode("Show comments");
                        a.appendChild(a_text);
                        b.appendChild(a)
                        div.appendChild(b);
                    }
                    div.style.border = "solid";
                    div.style.borderWidth = "1px";
                    return div;
                } else if (this.type === "form"){
                    console.log("I am formed!");
                    const commentForm = document.createElement("form");
                    commentForm.setAttribute("method","post");
                    commentForm.setAttribute("action","");
                    commentForm.setAttribute("id", `response_form_${id}`)

                    textArea = document.createElement("textarea");
                    textArea.setAttribute("placeholder","Type your comment!");

                    submit = document.createElement("input");
                    submit.setAttribute("type","button");
                    submit.setAttribute("value","Send");

                    commentForm.appendChild(textArea);
                    commentForm.appendChild(submit);
                    submit.setAttribute("onclick", `sendComment(${this.id});return false;`);
                    return commentForm;
                }
            }
            return responseElement.create()
        }
    }

    const CommentResponse = function () {
        this.type = "response";
    };

    const CommentForm = function(){
        this.type = "form";
    }

    function getCSRFToken(){
        let cookies = document.cookie.split(";")
                .map(c => c.trim())
                .filter(c => c.startsWith("csrftoken="));
            let csrf_token = decodeURIComponent(cookies[0].split("=")[1])
            return csrf_token;
    }

    function createHeaders(){
        return {
            'Content-Type' :'application/json; charset=UTF-8',
            'X-CSRFToken' : getCSRFToken()
        }
    }

    function sendComment(id){

        let form = document.getElementById(`response_form_${id}`);

        const headers = createHeaders();

        fetch(`http://127.0.0.1:8000/articles/article/response_to_response/${id}`, {
            method: "POST",
            headers: headers,
            body: JSON.stringify({
                'content': form.children[0].value
            })
            }).then( r => {
                console.log("Response is: " + r);
                return r.json();
            })
            .then(
                r => console.log(r.post)
            )
            .catch(error => {
                console.log(error);
            });

            form.remove()
    }

    function createCommentForm(id, url){
        let doesFormExist = !!document.getElementById(`response_form_${id}`);

        if (doesFormExist){
            return;
        }

        let current_response = document.getElementById(`response_${id}`);
        commentForm = new responseFactory().createElement("form", undefined, id, undefined);
        current_response.appendChild(commentForm);
    }

    function fetchResponses(id, url){
        console.log("click");
        let current_response = document.getElementById(`response_${id}`);
        let cid = 3
        //let response_url = "{% url 'arts:all_responses_to_response' 111 %}";
        new_url= createResponseUrl(id);
        console.log(new_url);

        fetch(new_url, {
            method : "GET"
        }).then(r => r.json())
        .then(json => json.forEach(j => {
                console.log(j);
                div = new responseFactory().createElement("response", j.body, j.id, j.commented);
                console.log(div);
                current_response.appendChild(div);
                }
             ))
        .catch(error => console.log(error));
    }

    const createResponseUrl = function(id){
        let templateUrl = "{% url 'arts:all_responses_to_response' 111 %}";
        return templateUrl.replace('111',id);
    }

    const createDeleteUrl = function(resp_id){
        let article = document.getElementsByClassName("article")[0];
        console.log("Id of article is: " + article.id);
    }



</script>

{% endblock %}

sci_phi_blog/arts/templates/arts/art_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form action="{% url 'arts:create_article' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    {{ form.media }}
    <input type="submit" value="Save" onclick="return false;">
    <input type="submit" onclick="console.log('clicked');">
</form>

{% endblock %}

sci_phi_blog/arts/templates/arts/art_list.html
{% extends "base_menu.html" %}

{% block title %}
Articles
{% endblock %}
{% block content %}

<div class="col-md-7 float-right">
  <h1>Arts</h1>
    {% if article_list %}
    <ul>
      {% for art in article_list %}
        <li>
          {{art.title}} - {{art.language}}<a href = "{% url 'arts:article' art.id %}">more</a>
          <br/>
          {% if user == art.author %}
          <a href="{% url 'arts:update_article' art.id%}"><i class="fa fa-pencil"></i></a>
          <a href="{% url 'arts:delete_article' art.id%}"><i class="fa fa-trash"></i></a>
          {% endif %}
          <br/>
          {{ art.snippet|safe}}
        </li>
        {% endfor %}
        {% endif %}
    {% endblock %}
    </ul>
</div>

sci_phi_blog/arts/templates/arts/art_update.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form action="{% url 'arts:update_article' art.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <input type="submit" onclick="console.log('clicked');">
</form>
{% endblock %}

sci_phi_blog/arts/templates/arts/article_delete_confirm.html
{% extends 'base_menu.html' %}
{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    <p>Are you sure that you want to delete this entry?</p>
    <input type ="submit" value="Yes" >
    <input type ="submit" value="No" onclick ="window.location.href={% url 'arts:all' %}; return false;">
</form>

{% endblock %}

sci_phi_blog/arts/templates/arts/enum_list.html
{% extends 'base_menu.html' %}
{% block content %}
<div class="row" style="width: 100%;">
    <div class="col-xs-12">

        <ul style="list-style-type: none;">
            {% for enum in enums %}
            <li><a href="#" id="{{lang}}" onclick="funFunction('{{enum}}'); return false;">{{enum}}</a></li>
            {% endfor %}
        </ul>
        <hr>
        <div class="mw-100"></div>
    </div>
</div>

    <script charset="UTF-16">
        function funFunction(lang){
            console.log(lang);
            fetch(`/articles/languages/${lang}`)
            .then(r => r.json())
            .then(jsons => { destroy();
                return jsons;})
            .then(jsons => {
                        article_row = document.createElement("div");
                        article_row.classList.add("row");
                        article_row.classList.add("articles");

                        article_col = document.createElement("div");
                        article_col.classList.add("col-xs-12");


                        article_list = document.createElement("ul");
                        jsons.forEach(json => {
                            console.log(json);
                            createArticle(json);
                                });
                        article_col.appendChild(article_list);
                        article_row.appendChild(article_col);

                        document.getElementById("content").appendChild(article_row);
                            })
            .catch(error => console.log(error));
        }

        function createArticle(json){
            let article_li = document.createElement("div");

            let article_link = document.createElement("a");
            article_link.href = `/articles/article/${json.id}`;
            article_link.innerHTML = json.title;

            article_li.appendChild(article_link);
            article_list.appendChild(article_li);
            console.log(json.title);



        }

        function destroy(){
            previous_arts = document.getElementsByClassName("articles");

            if (previous_arts.length !== 0){
                console.log(previous_arts);
                for (let i = 0; i < previous_arts.length; i++){
                    previous_arts[i].style.display = "none";
                }
            }
        }
    </script>

{% endblock %}

sci_phi_blog/arts/templates/arts/response_delete_confirm.html
{% extends 'base_menu.html' %}
{% block content %}
<h1>Are you sure that you want to delete your response?</h1>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" onsubmit="{% url 'arts:all' %}" value="Yes">
    <input type="submit" onsubmit="{% url 'arts:all' %}" value="No">
</form>

{% endblock %}

sci_phi_blog/arts/templates/arts/response_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save changes">
    </form>
</body>
</html>