sci_phi_blog/accs/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import UserCreateView, UserRegisterView, UserChangeView, AccountChangePasswordView, UserProfileView, \
    EditUserProfileView, EditUserProfileSettingsView, CreateUserProfileView, SaveJSONView

urlpatterns = [
    path('create_user', UserCreateView.as_view(), name="create_user"),
    path('register', UserRegisterView.as_view(), name='register'),
    path('edit', UserChangeView.as_view(), name="edit_user"),
    path('create/profile', CreateUserProfileView.as_view(), name='create_profile'),
    path('<int:pk>/profile', UserProfileView.as_view(), name="profile_page"),
    path('<int:pk>/profile/edit_profile', EditUserProfileView.as_view(), name="edit_profile_page"),
    path('<int:pk>/profile/save', SaveJSONView.as_view(), name="save_json"),
    path('profile_settings', EditUserProfileSettingsView.as_view(), name="edit_profile"),
]

sci_phi_blog/arts/urls.py
from .views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, \
    show_categories, show_languages, ArticleByLanguageView, ResponseView, ResponseUpdateView, ResponseDeleteView, \
    ResponseToResponseView, ShowResponsesToResponseView
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'arts'

urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create_article'),
    path('all/', ArticleListView.as_view(), name = 'all'),
    path('all/categories', show_categories, name ='categories'),
    path('all/languages', show_languages, name='languages'),
    path('article/<int:pk>', ArticleDetailView.as_view(), name='article'),
    path('article/<int:pk>/update', ArticleUpdateView.as_view(), name='update_article'),
    path('article/<int:pk>/delete', ArticleDeleteView.as_view(), name='delete_article'),
    path('article/<int:pk>/response', ResponseView.as_view(), name='comment_article'),
    path('article/<int:pk>/response/<int:pk_2>', ResponseUpdateView.as_view(), name='update_comment'),
    path('article/<int:pk>/response/<int:pk_2>/delete', ResponseDeleteView.as_view(), name='delete_comment'),
    path('article/response_to_response/<int:pk>', ResponseToResponseView.as_view(), name='response_to_response'),
    path('article/response_to_response/<int:pk>/all_responses', ShowResponsesToResponseView.as_view(), name='all_responses_to_response'),
    path('languages/<str:lang>', ArticleByLanguageView.as_view(), name='articles_by_lang'),
]

sci_phi_blog/home/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import MainView, AboutView;

urlpatterns = [
    path('', MainView.as_view(), name="home"),
    path('about/', AboutView.as_view(), name="about"),
]

sci_phi_blog/sci_phi_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static

from accs.views import AccountChangePasswordView

app_name = "home"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('user/', include('accs.urls')),
    path('articles/', include('arts.urls')),
    path('user/profile/', views.profile_redirect, name='profile_redirect'),
    path('password/', AccountChangePasswordView.as_view(), name="password"),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sci_phi_blog/home/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView

class MainView(TemplateView):
    template_name = "home\\main.html";

class AboutView(TemplateView):
    template_name = "home\\about.html";

sci_phi_blog/home/templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>
<!-- Edit dj4e-samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<!-- Replace this value (42-42) with the one provided by the autograder -->
<meta name="dj4e" content="14318e2a43a225fc24ab55f3c0122cf0" charset="UTF-8">

<meta name="dj4e-code" content="42163123647402">

    {% load static %}
    <link rel="stylesheet"
          href="{% static 'styles.css' %}"
          type="text/css">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

<meta name="dj4e-version" content="2021-04-14">

{% block head %} {% endblock %}

</head>
<body>
<div class="container-fluid" style="padding-right: 0px;
                padding-left: 0px;">
{% block navbar_and_content %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}

</div>
{% block footer %} {% endblock %}
</body>
</html>

sci_phi_blog/home/templates/base_menu.html
{% extends "base_bootstrap.html" %}
{% block title %}
Kermeline...
{% endblock %}
{% block navbar_and_content %}
{% load app_tags %}
<nav class="navbar navbar-default navbar-inverse mw-100" style="z-index: 999;">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/">{{ settings.APP_NAME }}</a>
    </div>
    <!-- https://stackoverflow.com/questions/22047251/django-dynamically-get-view-url-and-check-if-its-the-current-page -->
    <ul class="nav navbar-nav mr-auto">
        <li {% if request.get_full_path == ads %}class="active nav-item"{% endif %}>
          <a href="{% url 'about' %}">About</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li class="nav-item">
            <a href="{% url 'arts:categories' %}">Categories</a>
        </li>
        <li class="nav-item">
            <a href="{% url 'arts:languages' %}">Languages</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle"
               href="#"
               id="navbarDropdown"
                role="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false">
                Profile
            </a>

            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% if user.profile.id %}
                <a class="dropdown-item" href="{% url 'edit_user' %}">Edit Settings<br/></a>
                <a class="dropdown-item" href="{% url 'edit_profile_page' user.profile.id %}">Edit Profile Page<br/></a>
                <a class="dropdown-item" href="{% url 'profile_page' user.profile.id%}">Show Profile Page<br/></a>
                {% else %}
                <a class="dropdown-item" href="{% url 'create_profile' %}">Create Profile</a>
                {% endif %}
            </div>
        </li>
        {% endif %}
        {% if user.is_authenticated %}
        <li class="nav-item">
        <a href="{% url 'arts:create_article' %}">Create Article</a>
        </li>
        <li class="nav-item">
            <div>
              <form action="{% url 'arts:all' %}" method = "get">

                    <input type="text" placeholder="search..." name="search" style="float: left" class="form-control">
                    <input type="submit"
                           class="btn btn-success float-right"
                           value="Browse" style="float: left">
                      <i class="fa fa-search"></i>
                      <a href="{% url 'arts:all' %}"><i class="fa fa-undo"></i></a>
              </form>
            </div>
        </li>
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                <img style="width: 25px;" src="{{ user|gravatar:60 }}"/><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="{% url 'logout' %}?next=#">Logout</a></li>
                <li><a href="{% url 'edit_user' %}">Edit Profile</a></li>
                <li><a href="#">Learn more</a></li>
            </ul>
        </li>
            {% else %}
            <li>
            <a href="{% url 'login' %}?next=#">Login</a>
            </li>
            <li>
                <a href="{% url 'register' %}?next={% url 'login' %}">Register</a>
            </li>
            {% endif %}
    </ul>
  </div>
</nav>
</div>
<div class="wrapper" style="width: 100%; display: flex; float: left;">
    <nav id="sidebar" class="navbar-nav navbar-right nav" style="height: 100vh; background: #24252B; color: #fff; width: 150px; left: 100; position: fixed;">
        <div id="left_navbar_div">
            <ul class="nav navbar-nav" id="left_bar">
              <li {% if request.get_full_path == ads %}class="active"{% endif %}>
                  <a href="#">Shizzm</a></li>
                <li {% if request.get_full_path == ads and user.is_superuser %}class="active"{% endif %}>
                    {% if user.is_superuser %}
                  <a href="{% url 'create_user' %}">User</a></li>
                    {% endif %}
            </ul>
        </div>
    </nav>
</div>
<div id="content" class="container" style="flex-direction: column;" >
    {% block content %} {% endblock %}
</div>

{% endblock %}